### PR TITLE
Stage react api

### PR DESCRIPTION
**Pull request by DmitriySlinkovenko**
Hello my reviewer, I have a couple of notes for you to createContext. This is only the front-end part of the project, so the login and signup and save card functionality is non-existent yet. But some placeholder text is included where the information from my back-end will come in the future. Thank you.

### CODE REVIEW

**Comment by FiLLa-FaS** [comment]
Hey! Thanks for sending your project for review, it already looks decent! I marked all issues below. Good luck!✨

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
    * Please note, that the project should have 4 different fonts and many font-faces, now several fonts and font-faces aren't rendered on the page, please make sure that all necessary font-faces of the fonts are added to the project and `font-family` styles are used with proper values
    * Mismatches of the home page on 1440px https://snipboard.io/intJx5.jpg
    * Mismatches of the home page on 768px https://snipboard.io/qcKB3a.jpg https://snipboard.io/HqSBZ3.jpg https://snipboard.io/t067wb.jpg https://snipboard.io/n6L13x.jpg https://snipboard.io/LK094Q.jpg
    * Mismatches of the home page on 320px https://snipboard.io/C7ZOE4.jpg https://snipboard.io/Upfe13.jpg
    * Incorrect height of the modal window on 320 viewport
    * Mismatches of the saved news page on 1440px https://snipboard.io/wTfp6S.jpg
    * Mismatches of the saved news page on 768px https://snipboard.io/EWr6n7.jpg
    * Mismatches of the saved news page on 320px https://snipboard.io/Ufcj9E.jpg
    * Please check all text properties inside the modal window
- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * The project should keep its width on more than 1440px screen resolutions without stretching
    * All project content should be centered horizontally on intermediate screen resolutions
    * Text content in `about` section shouldn't be too narrow on intermediate screen resolutions (every row should contain more than 1-2 words)
- [ ]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
    * Facebook link shouldn't lead to the project
- [ ]  Classes are named according to BEM specifications.
    * Please don't use BEM elements outside their blocks, for example `mobile-header__container` can't be used outside the `mobile-header` block. Please fix all similar cases **throughout the project**
    * `form__redirect-btn_span` should be a BEM element
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid` layouts are used to arrange elements whenever applicable.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [ ]  There are no linting errors or warnings.
    * Project has several eslint errors and warnings

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
    * All buttons should have pointer cursor
    * Show more button should have hover state
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [ ]  System fonts are connected as alternatives to each of your fonts.
    * Not all `font-family` styles have alternative fonts
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 50

**Comment by FiLLa-FaS** [comment]
Hey! Thanks for the corrections, your project looks much better! Several small issues below are left. Good luck!✨

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
    * Please note, that the project should have 4 different fonts and many font-faces, now several fonts and font-faces aren't rendered on the page, please make sure that all necessary font-faces of the fonts are added to the project and font-family styles are used with proper values
    * Modal switch button shouldn't go outside the modal window on desktop screen resolutions
    * Mismatches of the home page on 768px https://snipboard.io/JHwav5.jpg
    * Mismatches of the home page on 320px https://snipboard.io/bOmA3Q.jpg https://snipboard.io/IuFwVQ.jpg
- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * The project should keep its width on more than 1440px screen resolutions without stretching
    * All project content should be centered horizontally on intermediate screen resolutions
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.
    * Please don't use BEM elements outside their blocks, for example `mobile-header__container` can't be used outside the `mobile-header` block. Please fix all similar cases throughout the project
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid` layouts are used to arrange elements whenever applicable.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
    * Search form button and modal close button should have pointer cursors
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [ ]  System fonts are connected as alternatives to each of your fonts.
    * `preloader__text` should have alternative fonts
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 67

**Comment by FiLLa-FaS** [comment]
Hey! Your project is almost finished, several small issues below are left. Good luck!

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
    * Please note, that the project should have 4 different fonts and many font-faces, now several fonts and font-faces aren't rendered on the page, please make sure that all necessary font-faces of the fonts are added to the project and font-family styles are used with proper values (now I see Arial font in headings)
- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * The project should keep its width on more than 1440px screen resolutions without stretching (please check the saved-news page
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.
    * Please don't use BEM elements outside their blocks, for example `saved-news__section` can't be used outside the `saved-news` block. Please fix all similar cases throughout the project
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid` layouts are used to arrange elements whenever applicable.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 70

**Comment by DmitriySlinkovenko** [comment]
I'm sorry, I can't seem to find where saved-news__section is being used except for SavedNews block

**Comment by FiLLa-FaS** [comment]
Hey Dmitriy! I'm glad to accept your project! Good luck on the next stage🥷🚀

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
- [x]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid` layouts are used to arrange elements whenever applicable.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 100

**Pull request merged**
